-- SQL skript pro hromadné vložení všech RSS zdrojů do scout_sources
-- Vygenerováno z rss-sources-flat.ts

insert into scout_sources (name, url, active)
values
  ('Billboard', 'https://www.billboard.com/feed/', true),
  ('HipHopDX Releases', 'https://hiphopdx.com/rss', true),
  ('Rap-Up', 'https://www.rap-up.com/feed/', true),
  ('Rolling Stone Music', 'https://www.rollingstone.com/music/feed/', true),
  ('Pitchfork News', 'https://pitchfork.com/rss/news/', true),
  ('HipHopDX', 'https://hiphopdx.com/feed', true),
  ('XXL', 'https://xxlmag.com/feed', true),
  ('HotNewHipHop', 'https://www.hotnewhiphop.com/rss.php', true),
  ('AllHipHop', 'https://allhiphop.com/feed', true),
  ('Genius News', 'https://genius.com/news/rss', true),
  ('The Source', 'https://thesource.com/feed', true),
  ('Rap Radar', 'https://rapradar.com/feed', true),
  ('Vibe', 'https://www.vibe.com/feed', true),
  ('Stereogum Hip-Hop', 'https://www.stereogum.com/category/hip-hop/feed/', true),
  ('Consequence', 'https://consequence.net/feed/', true),
  ('GRM Daily', 'https://grmdaily.com/feed', true),
  ('Mixtape Madness', 'https://mixtapemadness.com/feed', true),
  ('Link Up TV', 'https://linkuptv.co.uk/feed', true),
  ('Refresher CZ', 'https://refresher.cz/rss', true),
  ('Rap Revue', 'https://raprevue.cz/feed', true),
  ('HipHop.cz', 'https://hiphop.cz/feed', true),
  ('iRadio Beat CZ', 'https://iradiobeat.cz/rss', true),
  ('Refresher SK', 'https://refresher.sk/rss', true),
  ('Flow SK', 'https://flow.sk/feed', true),
  ('Backspin', 'https://backspin.de/feed', true),
  ('HipHop.de', 'https://hiphop.de/rss', true),
  ('Juice Magazine', 'https://juice.de/feed', true),
  ('16BARS.de', 'https://16bars.de/feed', true),
  ('Rap.de', 'https://rap.de/feed', true),
  ('Booska-P', 'https://www.booska-p.com/rss', true),
  ('Raplume', 'https://raplume.eu/feed', true),
  ('Abcdr du Son', 'https://www.abcdrduson.com/feed', true),
  ('Rap Genius FR', 'https://genius.com/fr/news/rss', true),
  ('Popkiller', 'https://popkiller.pl/rss', true),
  ('WhiteHouse PL', 'https://whitehouse.com.pl/feed', true),
  ('HipHop Centrum', 'https://hiphopcen.pl/feed', true),
  ('HiphopTV', 'https://hiphoptv.it/feed', true),
  ('HipHop.es', 'https://hiphopes.es/feed', true),
  ('FunX NL', 'https://www.funx.nl/rss', true),
  ('TMZ', 'https://www.tmz.com/rss.xml', true),
  ('WorldStar', 'https://worldstarhiphop.com/rss', true),
  ('MediaTakeOut', 'https://mtonews.com/feed', true),
  ('Bossip', 'https://bossip.com/feed', true),
  ('The Shade Room', 'https://theshaderoom.com/feed', true),
  ('HipHopHeads', 'https://www.reddit.com/r/hiphopheads/.rss', true),
  ('PopCultureChat', 'https://www.reddit.com/r/PopCultureChat/.rss', true),
  ('Daily Mail US', 'https://www.dailymail.co.uk/ushome/index.rss', true),
  ('Blesk', 'https://www.blesk.cz/rss', true),
  ('Pluska', 'https://www.pluska.sk/rss', true),
  ('Bild', 'https://www.bild.de/rssfeeds/vw-home/vw-home-16725546,feed=home.bild.html', true),
  ('Closer', 'https://www.closermag.fr/rss', true),
  ('Fakt', 'https://www.fakt.pl/rss', true),
  ('Chi', 'https://www.chimagazine.it/rss', true),
  ('Hypebeast', 'https://hypebeast.com/feed', true),
  ('Highsnobiety', 'https://www.highsnobiety.com/feed', true),
  ('Sneaker News', 'https://sneakernews.com/feed', true),
  ('Sole Collector', 'https://solecollector.com/feed', true),
  ('Kicks On Fire', 'https://www.kicksonfire.com/feed', true),
  ('Nice Kicks', 'https://www.nicekicks.com/feed', true),
  ('Vogue', 'https://www.vogue.com/feed', true),
  ('GQ', 'https://www.gq.com/feed', true),
  ('Business of Fashion', 'https://www.businessoffashion.com/rss', true),
  ('Complex Style', 'https://www.complex.com/style/rss', true),
  ('Hype.cz', 'https://hype.cz/feed', true),
  ('Street Machine', 'https://streetmachine.cz/feed', true),
  ('BBC News', 'https://feeds.bbci.co.uk/news/rss.xml', true),
  ('Al Jazeera', 'https://www.aljazeera.com/xml/rss/all.xml', true),
  ('Reuters', 'https://feeds.reuters.com/reuters/topNews', true),
  ('France 24', 'https://www.france24.com/en/rss', true),
  ('Euronews', 'https://www.euronews.com/rss', true),
  ('NPR', 'https://www.npr.org/rss/rss.php?id=1001', true),
  ('The Guardian World', 'https://www.theguardian.com/world/rss', true),
  ('CNN', 'https://rss.cnn.com/rss/edition.rss', true),
  ('Novinky.cz', 'https://www.novinky.cz/rss', true),
  ('iDNES.cz', 'https://servis.idnes.cz/rss.aspx?c=zpravodaj', true),
  ('Pravda SK', 'https://spravy.pravda.sk/rss', true),
  ('Spiegel', 'https://www.spiegel.de/international/index.rss', true),
  ('Le Monde', 'https://www.lemonde.fr/rss/une.xml', true),
  ('Gazeta Wyborcza', 'https://wyborcza.pl/pub/rss/wyborcza.xml', true),
  ('Corriere della Sera', 'https://rss.corriere.it/rss/homepage.xml', true),
  ('Complex', 'https://complex.com/music/rss', true),
  ('The Fader', 'https://www.thefader.com/rss', true),
  ('Mass Appeal', 'https://massappeal.com/feed', true),
  ('DJBooth', 'https://djbooth.net/feed', true),
  ('Knowledge Mag', 'https://knowledgemagazine.co.uk/feed', true),
  ('Notion Mag', 'https://notion.online/feed', true),
  ('Reddit Memes', 'https://www.reddit.com/r/memes/.rss', true),
  ('Reddit DankMemes', 'https://www.reddit.com/r/dankmemes/.rss', true),
  ('Know Your Meme', 'https://knowyourmeme.com/rss', true),
  ('The Poke', 'https://www.thepoke.co.uk/feed/', true),
  ('Upworthy', 'https://www.upworthy.com/feed', true),
  ('BuzzFeed', 'https://www.buzzfeed.com/world.xml', true),
  ('Musicserver', 'https://musicserver.cz/rss', true),
  ('Reflex', 'https://www.reflex.cz/rss', true),
  ('Kapital SK', 'https://kapital.sk/rss', true),
  ('Život SK', 'https://zivot.pluska.sk/rss', true),
  ('MZEE.com', 'https://mzee.com/magazine/feed', true),
  ('Focus DE', 'https://www.focus.de/feeds/rss/gesellschaft', true),
  ('Yard FR', 'https://www.yard.live/feed', true),
  ('GEO FR', 'https://www.geo.fr/rss', true),
  ('AllMusic Italia', 'https://allmusicitalia.it/feed', true),
  ('Rockit', 'https://www.rockit.it/feed', true),
  ('Bass Culture', 'https://bassculturemagazine.com/feed', true),
  ('3voor12', 'https://3voor12.vpro.nl/rss', true),
  ('Gaffa SE', 'https://gaffa.se/rss', true),
  ('National Geo PL', 'https://www.national-geographic.pl/rss', true),
  ('MIT Tech Review', 'https://www.technologyreview.com/feed', true),
  ('TechCrunch', 'https://techcrunch.com/feed', true),
  ('Nature', 'https://www.nature.com/nature.rss', true),
  ('Wired Science', 'https://www.wired.com/feed/category/science/latest/rss', true),
  ('Věda24 CZ', 'https://www.ceskatelevize.cz/rss/veda24/', true),
  ('Quark SK', 'https://www.quark.sk/rss', true),
  ('Spektrum DE', 'https://www.spektrum.de/rss/spektrum-rss2.xml', true),
  ('Sciences et Avenir', 'https://www.sciencesetavenir.fr/rss.xml', true),
  ('Nauka w Polsce', 'https://naukawpolsce.pl/rss.xml', true),
  ('Le Scienze', 'https://www.lescienze.it/rss', true),
  ('Rapzname CZ', 'https://rapzname.cz/feed', true),
  ('iReport CZ', 'https://www.ireport.cz/rss', true),
  ('Raps.sk', 'https://raps.sk/feed', true),
  ('Cas.sk', 'https://www.cas.sk/rss', true),
  ('Rapologia IT', 'https://www.rapologia.it/feed', true),
  ('Gossip.it', 'https://www.gossip.it/rss', true),
  ('HHGroups ES', 'https://www.hhgroups.com/rss', true),
  ('20 Minutos ES', 'https://www.20minutos.es/rss', true),
  ('Bild DE', 'https://www.bild.de/rss', true),
  ('Gala FR', 'https://www.gala.fr/rss', true),
  ('Puna NL', 'https://www.puna.nl/feed/', true),
  ('Telegraaf NL', 'https://www.telegraaf.nl/rss', true),
  ('Plotek PL', 'https://www.plotek.pl/rss', true),
  ('Daily Mail UK', 'https://www.dailymail.co.uk/articles.rss', true),
  ('The Flow RU', 'https://the-flow.ru/rss', true),
  ('Lenta RU', 'https://lenta.ru/rss', true),
  ('Mondo RS', 'https://mondo.rs/rss', true),
  ('Telegraf RS', 'https://telegraf.rs/rss', true),
  ('Top Channel AL', 'https://top-channel.tv/rss', true),
  ('Zeri AL', 'https://zeri.info/rss', true),
  ('Klix BA', 'https://klix.ba/rss', true),
  ('Avaz BA', 'https://avaz.ba/rss', true),
  ('Index HR', 'https://www.index.hr/rss', true),
  ('24sata HR', 'https://www.24sata.hr/rss', true),
  ('Pitchfork Reviews', 'https://pitchfork.com/rss/reviews/albums/', true),
  ('Stereogum', 'https://www.stereogum.com/feed/', true),
  ('Reddit IIB', 'https://www.reddit.com/r/InternetIsBeautiful/.rss', true)
on conflict (url) do nothing;
