alter table scout_items add column if not exists language_detected text;
alter table scout_items add column if not exists english_master    text;
alter table feed_posts  add column if not exists english_master     text;
alter table feed_posts  add column if not exists localized_versions jsonb not null default '{}';
alter table posts       add column if not exists english_master     text;
alter table posts       add column if not exists localized_versions jsonb not null default '{}';
create index if not exists idx_scout_items_language on scout_items(language_detected);

alter table scout_items add column if not exists priority     text    default 'P3';
alter table scout_items add column if not exists is_release   boolean not null default false;
alter table scout_items add column if not exists release_type text;
create index if not exists idx_scout_items_priority   on scout_items(priority);
create index if not exists idx_scout_items_is_release on scout_items(is_release) where is_release = true;

alter table scout_sources drop constraint if exists scout_sources_category_check;
alter table scout_sources add  constraint scout_sources_category_check
  check (category in ('droppz_news','rap_core','deep_scout','drama','fashion','global_news','culture','science'));

alter table scout_sources drop constraint if exists scout_sources_lang_check;
alter table scout_sources add  constraint scout_sources_lang_check
  check (lang in ('cs','sk','de','fr','pl','it','es','nl','se','ru','sr','sq','bs','hr','en-gb','en-us','global'));

insert into scout_sources (name, url, category, lang, active) values
  ('Billboard',            'https://www.billboard.com/feed/',                                          'droppz_news', 'en-us', true),
  ('HipHopDX Releases',    'https://hiphopdx.com/rss',                                                'droppz_news', 'en-us', true),
  ('Rap-Up',               'https://www.rap-up.com/feed/',                                             'droppz_news', 'en-us', true),
  ('Rolling Stone Music',  'https://www.rollingstone.com/music/feed/',                                 'droppz_news', 'en-us', true),
  ('Pitchfork News',       'https://pitchfork.com/rss/news/',                                          'droppz_news', 'en-us', true),
  ('HipHopDX',             'https://hiphopdx.com/feed',                                                'rap_core', 'en-us', true),
  ('XXL',                  'https://xxlmag.com/feed',                                                  'rap_core', 'en-us', true),
  ('HotNewHipHop',         'https://www.hotnewhiphop.com/rss.php',                                     'rap_core', 'en-us', true),
  ('AllHipHop',            'https://allhiphop.com/feed',                                               'rap_core', 'en-us', true),
  ('Genius News',          'https://genius.com/news/rss',                                              'rap_core', 'en-us', true),
  ('The Source',           'https://thesource.com/feed',                                               'rap_core', 'en-us', true),
  ('Rap Radar',            'https://rapradar.com/feed',                                                'rap_core', 'en-us', true),
  ('Vibe',                 'https://www.vibe.com/feed',                                                'rap_core', 'en-us', true),
  ('Stereogum Hip-Hop',    'https://www.stereogum.com/category/hip-hop/feed/',                         'rap_core', 'en-us', true),
  ('Consequence',          'https://consequence.net/feed/',                                             'rap_core', 'en-us', true),
  ('GRM Daily',            'https://grmdaily.com/feed',                                                'rap_core', 'en-gb', true),
  ('Mixtape Madness',      'https://mixtapemadness.com/feed',                                          'rap_core', 'en-gb', true),
  ('Link Up TV',           'https://linkuptv.co.uk/feed',                                              'rap_core', 'en-gb', true),
  ('Refresher CZ',         'https://refresher.cz/rss',                                                'rap_core',  'cs', true),
  ('Rap Revue',            'https://raprevue.cz/feed',                                                 'rap_core', 'cs', true),
  ('HipHop.cz',            'https://hiphop.cz/feed',                                                   'rap_core', 'cs', true),
  ('iRadio Beat CZ',       'https://iradiobeat.cz/rss',                                                'rap_core', 'cs', true),
  ('Refresher SK',         'https://refresher.sk/rss',                                                'rap_core', 'sk', true),
  ('Flow SK',              'https://flow.sk/feed',                                                     'rap_core', 'sk', true),
  ('Backspin',             'https://backspin.de/feed',                                                 'rap_core', 'de', true),
  ('HipHop.de',            'https://hiphop.de/rss',                                                    'rap_core', 'de', true),
  ('Juice Magazine',       'https://juice.de/feed',                                                     'rap_core', 'de', true),
  ('16BARS.de',            'https://16bars.de/feed',                                                    'rap_core', 'de', true),
  ('Rap.de',               'https://rap.de/feed',                                                      'rap_core', 'de', true),
  ('Booska-P',             'https://www.booska-p.com/rss',                                             'rap_core', 'fr', true),
  ('Raplume',              'https://raplume.eu/feed',                                                   'rap_core', 'fr', true),
  ('Abcdr du Son',         'https://www.abcdrduson.com/feed',                                          'rap_core', 'fr', true),
  ('Rap Genius FR',        'https://genius.com/fr/news/rss',                                           'rap_core', 'fr', true),
  ('Popkiller',            'https://popkiller.pl/rss',                                                 'rap_core', 'pl', true),
  ('WhiteHouse PL',        'https://whitehouse.com.pl/feed',                                           'rap_core', 'pl', true),
  ('HipHop Centrum',       'https://hiphopcen.pl/feed',                                                'rap_core', 'pl', true),
  ('HiphopTV',             'https://hiphoptv.it/feed',                                                 'rap_core', 'it', true),
  ('HipHop.es',            'https://hiphopes.es/feed',                                                 'rap_core', 'es', true),
  ('FunX NL',              'https://www.funx.nl/rss',                                                  'rap_core', 'nl', true),
  ('TMZ',                  'https://www.tmz.com/rss.xml',                                              'drama', 'en-us', true),
  ('WorldStar',            'https://worldstarhiphop.com/rss',                                          'drama', 'en-us', true),
  ('MediaTakeOut',         'https://mtonews.com/feed',                                                 'drama', 'en-us', true),
  ('Bossip',               'https://bossip.com/feed',                                                  'drama', 'en-us', true),
  ('The Shade Room',       'https://theshaderoom.com/feed',                                            'drama', 'en-us', true),
  ('HipHopHeads',          'https://www.reddit.com/r/hiphopheads/.rss',                                'drama', 'en-us', true),
  ('PopCultureChat',       'https://www.reddit.com/r/PopCultureChat/.rss',                             'drama', 'en-us', true),
  ('Daily Mail US',        'https://www.dailymail.co.uk/ushome/index.rss',                             'drama', 'en-us', true),
  ('Blesk',                'https://www.blesk.cz/rss',                                                 'drama', 'cs', true),
  ('Pluska',               'https://www.pluska.sk/rss',                                                'drama', 'sk', true),
  ('Bild',                 'https://www.bild.de/rssfeeds/vw-home/vw-home-16725546,feed=home.bild.html','drama', 'de', true),
  ('Closer',               'https://www.closermag.fr/rss',                                             'drama', 'fr', true),
  ('Fakt',                 'https://www.fakt.pl/rss',                                                  'drama', 'pl', true),
  ('Chi',                  'https://www.chimagazine.it/rss',                                           'drama', 'it', true),
  ('Hypebeast',            'https://hypebeast.com/feed',                                               'fashion', 'global', true),
  ('Highsnobiety',         'https://www.highsnobiety.com/feed',                                        'fashion', 'global', true),
  ('Sneaker News',         'https://sneakernews.com/feed',                                             'fashion', 'global', true),
  ('Sole Collector',       'https://solecollector.com/feed',                                           'fashion', 'global', true),
  ('Kicks On Fire',        'https://www.kicksonfire.com/feed',                                         'fashion', 'global', true),
  ('Nice Kicks',           'https://www.nicekicks.com/feed',                                           'fashion', 'global', true),
  ('Vogue',                'https://www.vogue.com/feed',                                               'fashion', 'global', true),
  ('GQ',                   'https://www.gq.com/feed',                                                  'fashion', 'global', true),
  ('Business of Fashion',  'https://www.businessoffashion.com/rss',                                    'fashion', 'global', true),
  ('Complex Style',        'https://www.complex.com/style/rss',                                        'fashion', 'en-us', true),
  ('Hype.cz',              'https://hype.cz/feed',                                                     'fashion', 'cs', true),
  ('Street Machine',       'https://streetmachine.cz/feed',                                            'fashion', 'cs', true),
  ('BBC News',             'https://feeds.bbci.co.uk/news/rss.xml',                                    'global_news', 'global', true),
  ('Al Jazeera',           'https://www.aljazeera.com/xml/rss/all.xml',                                'global_news', 'global', true),
  ('Reuters',              'https://feeds.reuters.com/reuters/topNews',                                 'global_news', 'global', true),
  ('France 24',            'https://www.france24.com/en/rss',                                          'global_news', 'global', true),
  ('Euronews',             'https://www.euronews.com/rss',                                             'global_news', 'global', true),
  ('NPR',                  'https://www.npr.org/rss/rss.php?id=1001',                                  'global_news', 'en-us', true),
  ('The Guardian World',   'https://www.theguardian.com/world/rss',                                    'global_news', 'en-us', true),
  ('CNN',                  'https://rss.cnn.com/rss/edition.rss',                                      'global_news', 'en-us', true),
  ('Novinky.cz',           'https://www.novinky.cz/rss',                                               'global_news', 'cs', true),
  ('iDNES.cz',             'https://servis.idnes.cz/rss.aspx?c=zpravodaj',                            'global_news', 'cs', true),
  ('Pravda SK',            'https://spravy.pravda.sk/rss',                                             'global_news', 'sk', true),
  ('Spiegel',              'https://www.spiegel.de/international/index.rss',                           'global_news', 'de', true),
  ('Le Monde',             'https://www.lemonde.fr/rss/une.xml',                                       'global_news', 'fr', true),
  ('Gazeta Wyborcza',      'https://wyborcza.pl/pub/rss/wyborcza.xml',                                 'global_news', 'pl', true),
  ('Corriere della Sera',  'https://rss.corriere.it/rss/homepage.xml',                                 'global_news', 'it', true),
  ('Complex',              'https://complex.com/music/rss',                                            'culture', 'en-us', true),
  ('The Fader',            'https://www.thefader.com/rss',                                             'culture', 'en-us', true),
  ('Mass Appeal',          'https://massappeal.com/feed',                                              'culture', 'en-us', true),
  ('DJBooth',              'https://djbooth.net/feed',                                                 'culture', 'en-us', true),
  ('Knowledge Mag',        'https://knowledgemagazine.co.uk/feed',                                     'culture', 'en-gb', true),
  ('Notion Mag',           'https://notion.online/feed',                                               'culture', 'en-gb', true),
  ('Reddit Memes',         'https://www.reddit.com/r/memes/.rss',                                      'culture', 'en-us', true),
  ('Reddit DankMemes',     'https://www.reddit.com/r/dankmemes/.rss',                                  'culture', 'en-us', true),
  ('Know Your Meme',       'https://knowyourmeme.com/rss',                                             'culture', 'en-us', true),
  ('The Poke',             'https://www.thepoke.co.uk/feed/',                                          'culture', 'en-gb', true),
  ('Upworthy',             'https://www.upworthy.com/feed',                                            'culture', 'en-us', true),
  ('BuzzFeed',             'https://www.buzzfeed.com/world.xml',                                       'culture', 'en-us', true),
  ('Musicserver',          'https://musicserver.cz/rss',                                               'culture', 'cs', true),
  ('Reflex',               'https://www.reflex.cz/rss',                                                'culture', 'cs', true),
  ('Kapital SK',           'https://kapital.sk/rss',                                                   'culture', 'sk', true),
  ('Zivot SK',             'https://zivot.pluska.sk/rss',                                              'culture', 'sk', true),
  ('MZEE.com',             'https://mzee.com/magazine/feed',                                          'culture', 'de', true),
  ('Focus DE',             'https://www.focus.de/feeds/rss/gesellschaft',                              'culture', 'de', true),
  ('Yard FR',              'https://www.yard.live/feed',                                               'culture', 'fr', true),
  ('GEO FR',               'https://www.geo.fr/rss',                                                   'culture', 'fr', true),
  ('AllMusic Italia',      'https://allmusicitalia.it/feed',                                           'culture', 'it', true),
  ('Rockit',               'https://www.rockit.it/feed',                                               'culture', 'it', true),
  ('Bass Culture',         'https://bassculturemagazine.com/feed',                                     'culture', 'es', true),
  ('3voor12',              'https://3voor12.vpro.nl/rss',                                              'culture', 'nl', true),
  ('Gaffa SE',             'https://gaffa.se/rss',                                                     'culture', 'se', true),
  ('National Geo PL',      'https://www.national-geographic.pl/rss',                                   'culture', 'pl', true),
  ('MIT Tech Review',      'https://www.technologyreview.com/feed',                                    'science', 'global', true),
  ('TechCrunch',           'https://techcrunch.com/feed',                                              'science', 'global', true),
  ('Nature',               'https://www.nature.com/nature.rss',                                        'science', 'global', true),
  ('Wired Science',        'https://www.wired.com/feed/category/science/latest/rss',                   'science', 'global', true),
  ('Veda24 CZ',            'https://www.ceskatelevize.cz/rss/veda24/',                                 'science', 'cs', true),
  ('Quark SK',             'https://www.quark.sk/rss',                                                 'science', 'sk', true),
  ('Spektrum DE',          'https://www.spektrum.de/rss/spektrum-rss2.xml',                            'science', 'de', true),
  ('Sciences et Avenir',   'https://www.sciencesetavenir.fr/rss.xml',                                  'science', 'fr', true),
  ('Nauka w Polsce',       'https://naukawpolsce.pl/rss.xml',                                          'science', 'pl', true),
  ('Le Scienze',           'https://www.lescienze.it/rss',                                             'science', 'it', true),
  ('Pitchfork Reviews',    'https://pitchfork.com/rss/reviews/albums/',                                'deep_scout', 'en-us', true),
  ('Stereogum',            'https://www.stereogum.com/feed/',                                          'deep_scout', 'en-us', true),
  ('Reddit IIB',           'https://www.reddit.com/r/InternetIsBeautiful/.rss',                        'deep_scout', 'en-us', true)
on conflict (url) do update set
  name     = excluded.name,
  category = excluded.category,
  lang     = excluded.lang,
  active   = excluded.active;
