-- Vytvoření tabulky scout_sources pokud neexistuje
CREATE TABLE IF NOT EXISTS scout_sources (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	url TEXT NOT NULL UNIQUE,
	category TEXT NOT NULL,
	lang TEXT NOT NULL,
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO scout_sources (name, url, category, lang, active) VALUES
('Refresher CZ', 'https://refresher.cz/rss', 'rap_core', 'cs', true),
('Rap Revue', 'https://raprevue.cz/feed', 'rap_core', 'cs', true),
('Musicserver', 'https://musicserver.cz/rss', 'culture', 'cs', true),
('HipHop.cz', 'https://hiphop.cz/feed', 'rap_core', 'cs', true),
('Street Machine', 'https://streetmachine.cz/feed', 'fashion', 'cs', true),
('iRadio Beat CZ', 'https://iradiobeat.cz/rss', 'rap_core', 'cs', true),
('Novinky.cz', 'https://www.novinky.cz/rss', 'global_news', 'cs', true),
('iDNES.cz', 'https://servis.idnes.cz/rss.aspx?c=zpravodaj', 'global_news', 'cs', true),
('Věda24', 'https://www.ceskatelevize.cz/rss/veda24/', 'science', 'cs', true),
('Blesk', 'https://www.blesk.cz/rss', 'drama', 'cs', true),
('Reflex', 'https://www.reflex.cz/rss', 'culture', 'cs', true),
('Refresher SK', 'https://refresher.sk/rss', 'rap_core', 'sk', true),
('Flow SK', 'https://flow.sk/feed', 'rap_core', 'sk', true),
('Kapital SK', 'https://kapital.sk/rss', 'culture', 'sk', true),
('Pravda', 'https://spravy.pravda.sk/rss', 'global_news', 'sk', true),
('Quark', 'https://www.quark.sk/rss', 'science', 'sk', true),
('Pluska', 'https://www.pluska.sk/rss', 'drama', 'sk', true),
('Život', 'https://zivot.pluska.sk/rss', 'culture', 'sk', true),
('Backspin', 'https://backspin.de/feed', 'rap_core', 'de', true),
('HipHop.de', 'https://hiphop.de/rss', 'rap_core', 'de', true),
('Juice Magazine', 'https://juice.de/feed', 'rap_core', 'de', true),
('16BARS.de', 'https://16bars.de/feed', 'rap_core', 'de', true),
('Rap.de', 'https://rap.de/feed', 'rap_core', 'de', true),
('MZEE.com', 'https://mzee.com/magazine/feed', 'culture', 'de', true),
('Spiegel', 'https://www.spiegel.de/international/index.rss', 'global_news', 'de', true),
('Spektrum', 'https://www.spektrum.de/rss/spektrum-rss2.xml', 'science', 'de', true),
('Bild', 'https://www.bild.de/rssfeeds/vw-home/vw-home-16725546,feed=home.bild.html', 'drama', 'de', true),
('Focus', 'https://www.focus.de/feeds/rss/gesellschaft', 'culture', 'de', true),
('Booska-P', 'https://www.booska-p.com/rss', 'rap_core', 'fr', true),
('Raplume', 'https://raplume.eu/feed', 'rap_core', 'fr', true),
('Abcdr du Son', 'https://www.abcdrduson.com/feed', 'rap_core', 'fr', true),
('Yard', 'https://www.yard.live/feed', 'culture', 'fr', true),
('Mouvement', 'https://mouvement.net/feed', 'culture', 'fr', true),
('Rap Genius FR', 'https://genius.com/fr/news/rss', 'rap_core', 'fr', true),
('Le Monde', 'https://www.lemonde.fr/rss/une.xml', 'global_news', 'fr', true),
('Sciences et Avenir', 'https://www.sciencesetavenir.fr/rss.xml', 'science', 'fr', true),
('Closer', 'https://www.closermag.fr/rss', 'drama', 'fr', true),
('GEO', 'https://www.geo.fr/rss', 'culture', 'fr', true),
('Popkiller', 'https://popkiller.pl/rss', 'rap_core', 'pl', true),
('WhiteHouse PL', 'https://whitehouse.com.pl/feed', 'rap_core', 'pl', true),
('HipHop Centrum', 'https://hiphopcen.pl/feed', 'rap_core', 'pl', true),
('Gazeta Wyborcza', 'https://wyborcza.pl/pub/rss/wyborcza.pl/pub/rss/wyborcza.xml', 'global_news', 'pl', true),
('Nauka w Polsce', 'https://naukawpolsce.pl/rss.xml', 'science', 'pl', true),
('Fakt', 'https://www.fakt.pl/rss', 'drama', 'pl', true),
('National Geographic PL', 'https://www.national-geographic.pl/rss', 'culture', 'pl', true),
('HiphopTV', 'https://hiphoptv.it/feed', 'rap_core', 'it', true),
('AllMusic Italia', 'https://allmusicitalia.it/feed', 'culture', 'it', true),
('Rockit', 'https://www.rockit.it/feed', 'culture', 'it', true),
('Corriere della Sera', 'https://rss.corriere.it/rss/homepage.xml', 'global_news', 'it', true),
('Le Scienze', 'https://www.lescienze.it/rss', 'science', 'it', true),
('Chi', 'https://www.chimagazine.it/rss', 'drama', 'it', true),
('Focus Italia', 'https://www.focus.it/rss', 'culture', 'it', true),
('HipHop.es', 'https://hiphopes.es/feed', 'rap_core', 'es', true),
('Bass Culture', 'https://bassculturemagazine.com/feed', 'culture', 'es', true),
('3voor12', 'https://3voor12.vpro.nl/rss', 'culture', 'nl', true),
('FunX NL', 'https://www.funx.nl/rss', 'rap_core', 'nl', true),
('Gaffa SE', 'https://gaffa.se/rss', 'culture', 'se', true),
('GRM Daily', 'https://grmdaily.com/feed', 'rap_core', 'en-gb', true),
('Mixtape Madness', 'https://mixtapemadness.com/feed', 'rap_core', 'en-gb', true),
('Link Up TV', 'https://linkuptv.co.uk/feed', 'rap_core', 'en-gb', true),
('Knowledge Mag', 'https://knowledgemagazine.co.uk/feed', 'culture', 'en-gb', true),
('Notion Mag', 'https://notion.online/feed', 'culture', 'en-gb', true),
('HipHopDX', 'https://hiphopdx.com/feed', 'rap_core', 'en-us', true),
('XXL', 'https://xxlmag.com/feed', 'rap_core', 'en-us', true),
('HotNewHipHop', 'https://www.hotnewhiphop.com/rss.php', 'rap_core', 'en-us', true),
('AllHipHop', 'https://allhiphop.com/feed', 'rap_core', 'en-us', true),
('Genius News', 'https://genius.com/news/rss', 'rap_core', 'en-us', true),
('The Source', 'https://thesource.com/feed', 'rap_core', 'en-us', true),
('Rap Radar', 'https://rapradar.com/feed', 'rap_core', 'en-us', true),
('Complex', 'https://complex.com/music/rss', 'culture', 'en-us', true),
('The Fader', 'https://www.thefader.com/rss', 'culture', 'en-us', true),
('Pitchfork', 'https://pitchfork.com/feed/feed.json', 'culture', 'en-us', true),
('Noisey / Vice', 'https://www.vice.com/en/topic/noisey/rss', 'culture', 'en-us', true),
('Mass Appeal', 'https://massappeal.com/feed', 'culture', 'en-us', true),
('DJBooth', 'https://djbooth.net/feed', 'culture', 'en-us', true),
('TMZ', 'https://www.tmz.com/rss.xml', 'drama', 'en-us', true),
('WorldStar', 'https://worldstarhiphop.com/rss', 'drama', 'en-us', true),
('MediaTakeOut', 'https://mtonews.com/feed', 'drama', 'en-us', true),
('Bossip', 'https://bossip.com/feed', 'drama', 'en-us', true),
('The Shade Room', 'https://theshaderoom.com/feed', 'drama', 'en-us', true),
('Hypebeast', 'https://hypebeast.com/feed', 'fashion', 'global', true),
('Highsnobiety', 'https://www.highsnobiety.com/feed', 'fashion', 'global', true),
('Sneaker News', 'https://sneakernews.com/feed', 'fashion', 'global', true),
('Sole Collector', 'https://solecollector.com/feed', 'fashion', 'global', true),
('Kicks On Fire', 'https://www.kicksonfire.com/feed', 'fashion', 'global', true),
('Nice Kicks', 'https://www.nicekicks.com/feed', 'fashion', 'global', true),
('Hype.cz', 'https://hype.cz/feed', 'fashion', 'cs', true),
('Reuters', 'https://feeds.reuters.com/reuters/topNews', 'global_news', 'global', true),
('BBC News', 'https://feeds.bbci.co.uk/news/rss.xml', 'global_news', 'global', true),
('Vice', 'https://www.vice.com/en/rss', 'global_news', 'global', true),
('MIT Tech Review', 'https://www.technologyreview.com/feed', 'science', 'global', true),
('TechCrunch', 'https://techcrunch.com/feed', 'science', 'global', true),
('Nature', 'https://www.nature.com/rss', 'science', 'global', true)
ON CONFLICT (url) DO NOTHING;