/**
 * Concrete Template Definitions
 * Pre-built templates for common content types
 */

import type { Template } from './base'

export const VIDEO_DROP_TEMPLATE: Template = {
  id: 'video_drop_v1',
  name: 'Video Drop Template',
  type: 'video_drop',
  description: 'For official music videos, visual releases, clips',
  category: 'droppz',
  applicableContentTypes: ['droppz', 'usa_rap', 'uk_rap', 'eu_rap', 'ru_rap', 'balkan_rap'],
  priority: 100,
  fields: [
    {
      name: 'headline',
      type: 'text',
      required: true,
      maxLength: 120,
      description: 'Main headline (e.g., "Drake - God\'s Plan Official Video")',
      writer: { generate: true, prompt: 'Write a catchy headline for this video release' },
    },
    {
      name: 'hook',
      type: 'text',
      required: true,
      maxLength: 160,
      description: 'Opening hook/teaser',
      writer: { generate: true, prompt: 'Write a compelling opening that hooks the reader' },
    },
    {
      name: 'body',
      type: 'text',
      required: true,
      maxLength: 500,
      description: 'Main article body (context, artist info, impact)',
      writer: { generate: true, prompt: 'Write detailed article about this video release' },
    },
    {
      name: 'cta_text',
      type: 'text',
      required: true,
      maxLength: 80,
      description: 'Call-to-action text',
      writer: { generate: true, prompt: 'Write a CTA encouraging users to watch' },
    },
    {
      name: 'main_image',
      type: 'image',
      required: true,
      description: 'Main video thumbnail/cover',
      creator: { generate: true, format: 'image' },
    },
    {
      name: 'gallery_images',
      type: 'gallery',
      required: false,
      description: 'Additional images (screenshots, artist photo, etc)',
      creator: { generate: true, format: 'gallery' },
    },
    {
      name: 'youtube_url',
      type: 'link',
      required: true,
      description: 'Official YouTube video link',
      enricher: { collect: true, sources: ['youtube'] },
    },
    {
      name: 'spotify_url',
      type: 'link',
      required: false,
      description: 'Spotify track link (if available)',
      enricher: { collect: true, sources: ['spotify'] },
    },
    {
      name: 'other_platforms',
      type: 'links',
      required: false,
      description: 'Apple Music, Genius, SoundCloud, etc',
      enricher: { collect: true, sources: ['apple_music', 'genius', 'tiktok'] },
    },
    {
      name: 'artist_name',
      type: 'metadata',
      required: true,
      description: 'Primary artist name',
    },
    {
      name: 'tags',
      type: 'metadata',
      required: true,
      description: 'Hashtags (e.g., #hotdroppz #videorelease)',
      writer: { generate: true },
    },
  ],
  metadata: {
    requiresImage: true,
    requiresAudio: false,
    requiresLinks: 1, // At least YouTube
    minClusterSize: 3,
  },
}

export const SINGLE_DROP_TEMPLATE: Template = {
  id: 'single_drop_v1',
  name: 'Single Drop Template',
  type: 'single_drop',
  description: 'For single track releases (music-focused, less about visuals)',
  category: 'droppz',
  applicableContentTypes: ['droppz', 'usa_rap', 'uk_rap', 'eu_rap'],
  priority: 90,
  fields: [
    {
      name: 'headline',
      type: 'text',
      required: true,
      maxLength: 100,
      description: 'Song release headline',
      writer: { generate: true },
    },
    {
      name: 'hook',
      type: 'text',
      required: true,
      maxLength: 150,
      description: 'Why this track matters (vibe, producer, feat, etc)',
      writer: { generate: true },
    },
    {
      name: 'body',
      type: 'text',
      required: true,
      maxLength: 400,
      description: 'Track details, production, artist commentary',
      writer: { generate: true },
    },
    {
      name: 'track_cover',
      type: 'image',
      required: true,
      description: 'Album art / track cover',
      creator: { generate: false, format: 'image' }, // Usually from source
    },
    {
      name: 'spotify_url',
      type: 'link',
      required: true,
      description: 'Spotify track link',
      enricher: { collect: true, sources: ['spotify'] },
    },
    {
      name: 'apple_music_url',
      type: 'link',
      required: false,
      description: 'Apple Music link',
      enricher: { collect: true, sources: ['apple_music'] },
    },
    {
      name: 'genius_url',
      type: 'link',
      required: false,
      description: 'Genius lyrics link',
      enricher: { collect: true, sources: ['genius'] },
    },
    {
      name: 'preview_clip',
      type: 'link',
      required: false,
      description: 'Short preview video / TikTok',
      enricher: { collect: true, sources: ['tiktok'] },
    },
    {
      name: 'artist_name',
      type: 'metadata',
      required: true,
      description: 'Artist(s) name',
    },
    {
      name: 'producer_info',
      type: 'metadata',
      required: false,
      description: 'Producer credits',
      enricher: { collect: true },
    },
    {
      name: 'tags',
      type: 'metadata',
      required: true,
      description: 'Hashtags',
      writer: { generate: true },
    },
  ],
  metadata: {
    requiresImage: true,
    requiresAudio: true,
    requiresLinks: 1,
  },
}

export const ALBUM_DROP_TEMPLATE: Template = {
  id: 'album_drop_v1',
  name: 'Album Drop Template',
  type: 'album_drop',
  description: 'For album/EP releases with tracklist and overview',
  category: 'droppz',
  applicableContentTypes: ['droppz'],
  priority: 95,
  fields: [
    {
      name: 'headline',
      type: 'text',
      required: true,
      maxLength: 100,
      description: 'Album release headline',
      writer: { generate: true },
    },
    {
      name: 'hook',
      type: 'text',
      required: true,
      maxLength: 150,
      description: 'Album significance, themes, expectations',
      writer: { generate: true },
    },
    {
      name: 'body',
      type: 'text',
      required: true,
      maxLength: 600,
      description: 'Full album review, tracklist highlights, production notes',
      writer: { generate: true },
    },
    {
      name: 'album_art',
      type: 'image',
      required: true,
      description: 'Album cover',
    },
    {
      name: 'tracklist_visual',
      type: 'gallery',
      required: false,
      description: 'Visual representation of tracklist',
      creator: { generate: true, format: 'gallery' },
    },
    {
      name: 'spotify_url',
      type: 'link',
      required: true,
      description: 'Spotify album link',
      enricher: { collect: true, sources: ['spotify'] },
    },
    {
      name: 'apple_music_url',
      type: 'link',
      required: false,
      description: 'Apple Music album link',
      enricher: { collect: true, sources: ['apple_music'] },
    },
    {
      name: 'artist_links',
      type: 'links',
      required: false,
      description: 'Artist social/streaming links',
      enricher: { collect: true },
    },
    {
      name: 'artist_name',
      type: 'metadata',
      required: true,
      description: 'Artist name',
    },
    {
      name: 'featured_artists',
      type: 'metadata',
      required: false,
      description: 'Featured artists on album',
      enricher: { collect: true },
    },
    {
      name: 'track_count',
      type: 'metadata',
      required: true,
      description: 'Number of tracks',
    },
    {
      name: 'duration_minutes',
      type: 'metadata',
      required: false,
      description: 'Total duration',
    },
    {
      name: 'tags',
      type: 'metadata',
      required: true,
      description: 'Hashtags',
      writer: { generate: true },
    },
  ],
  metadata: {
    requiresImage: true,
    requiresAudio: true,
    requiresLinks: 1,
    minClusterSize: 5,
  },
}

export const GLOBAL_NEWS_TEMPLATE: Template = {
  id: 'global_news_v1',
  name: 'Global News Article',
  type: 'global_news',
  description: 'For general industry news, events, announcements',
  category: 'news',
  applicableContentTypes: ['news', 'interview', 'festival', 'tour'],
  priority: 80,
  fields: [
    {
      name: 'headline',
      type: 'text',
      required: true,
      maxLength: 120,
      description: 'Breaking news headline',
      writer: { generate: true },
    },
    {
      name: 'summary',
      type: 'text',
      required: true,
      maxLength: 200,
      description: 'Quick summary (3-4 sentences)',
      writer: { generate: true },
    },
    {
      name: 'body',
      type: 'text',
      required: true,
      maxLength: 800,
      description: 'Full news article with context and analysis',
      writer: { generate: true },
    },
    {
      name: 'featured_image',
      type: 'image',
      required: false,
      description: 'Primary news image',
      creator: { generate: true, format: 'image' },
    },
    {
      name: 'supporting_images',
      type: 'gallery',
      required: false,
      description: 'Additional context images',
    },
    {
      name: 'source_links',
      type: 'links',
      required: true,
      description: 'Original news sources',
      enricher: { collect: true },
    },
    {
      name: 'related_artists',
      type: 'metadata',
      required: false,
      description: 'Key artists involved',
    },
    {
      name: 'related_events',
      type: 'metadata',
      required: false,
      description: 'Event links if applicable',
      enricher: { collect: true },
    },
    {
      name: 'tags',
      type: 'metadata',
      required: true,
      description: 'Hashtags for discovery',
      writer: { generate: true },
    },
  ],
  metadata: {
    requiresImage: false,
    requiresAudio: false,
    requiresLinks: 1,
  },
}

export const TEMPLATES: Template[] = [
  VIDEO_DROP_TEMPLATE,
  SINGLE_DROP_TEMPLATE,
  ALBUM_DROP_TEMPLATE,
  GLOBAL_NEWS_TEMPLATE,
]

export const TEMPLATE_MAP: Record<string, Template> = {
  video_drop_v1: VIDEO_DROP_TEMPLATE,
  single_drop_v1: SINGLE_DROP_TEMPLATE,
  album_drop_v1: ALBUM_DROP_TEMPLATE,
  global_news_v1: GLOBAL_NEWS_TEMPLATE,
}
