-- ──────────────────────────────────────────────────────────────────────────────
-- Missing tables for auditor system
-- ──────────────────────────────────────────────────────────────────────────────

-- ──────────────────────────────────────────────────────────────────────────────
-- hd_templates: Content generation templates
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists hd_templates (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  description     text,
  prompt          text,
  model           text default 'gpt-4',
  active          boolean not null default true,
  created_at      timestamptz not null default now()
);

create index if not exists hd_templates_active_idx on hd_templates (active);

-- ──────────────────────────────────────────────────────────────────────────────
-- factory_runs: Record of content generation executions
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists factory_runs (
  id              uuid primary key default gen_random_uuid(),
  template_id     uuid references hd_templates (id) on delete set null,
  status          text not null default 'running', -- running | success | error
  articles_count  integer default 0,
  error_message   text,
  started_at      timestamptz not null default now(),
  completed_at    timestamptz,
  duration_ms     integer
);

create index if not exists factory_runs_status_idx on factory_runs (status);
create index if not exists factory_runs_started_at_idx on factory_runs (started_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- generated_articles: Content generated by writer
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists generated_articles (
  id              uuid primary key default gen_random_uuid(),
  title           text not null,
  body            text not null,
  summary         text,
  category        text,
  source_cluster  uuid,
  status          text default 'draft', -- draft | approved | published | failed
  error_message   text,
  created_at      timestamptz not null default now()
);

create index if not exists generated_articles_status_idx on generated_articles (status);
create index if not exists generated_articles_created_at_idx on generated_articles (created_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- distribution_queue: Items waiting for platform distribution
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists distribution_queue (
  id              uuid primary key default gen_random_uuid(),
  article_id      uuid references generated_articles (id) on delete cascade,
  platform        text not null, -- instagram | twitter | tiktok | facebook | etc
  status          text not null default 'pending', -- pending | queued | sent | failed
  post_url        text,
  error_message   text,
  created_at      timestamptz not null default now(),
  sent_at         timestamptz
);

create index if not exists distribution_queue_status_idx on distribution_queue (status);
create index if not exists distribution_queue_platform_idx on distribution_queue (platform);
create index if not exists distribution_queue_created_at_idx on distribution_queue (created_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- audit_runs: Audit execution history
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists audit_runs (
  id              uuid primary key default gen_random_uuid(),
  scope           text default 'full_system', -- full_system | full_pipeline | custom
  scope_detail    jsonb, -- { stages: ['sources', 'scout', ...] }
  overall_score   integer,
  issue_count     integer,
  critical_count  integer,
  high_count      integer,
  medium_count    integer,
  low_count       integer,
  created_at      timestamptz not null default now()
);

create index if not exists audit_runs_created_at_idx on audit_runs (created_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- error_logs: System error tracking
-- ──────────────────────────────────────────────────────────────────────────────
create table if not exists error_logs (
  id              uuid primary key default gen_random_uuid(),
  stage           text not null, -- sources | scout | cluster | factory | writer | feed | distribution | governance
  severity        text not null, -- critical | high | medium | low
  title           text not null,
  message         text,
  details         jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists error_logs_stage_idx on error_logs (stage);
create index if not exists error_logs_severity_idx on error_logs (severity);
create index if not exists error_logs_created_at_idx on error_logs (created_at desc);

-- ──────────────────────────────────────────────────────────────────────────────
-- RLS
-- ──────────────────────────────────────────────────────────────────────────────
alter table hd_templates        enable row level security;
alter table factory_runs        enable row level security;
alter table generated_articles  enable row level security;
alter table distribution_queue  enable row level security;
alter table audit_runs          enable row level security;
alter table error_logs          enable row level security;

create policy "auth_all_hd_templates"        on hd_templates        for all to authenticated using (true) with check (true);
create policy "auth_all_factory_runs"        on factory_runs        for all to authenticated using (true) with check (true);
create policy "auth_all_generated_articles"  on generated_articles  for all to authenticated using (true) with check (true);
create policy "auth_all_distribution_queue"  on distribution_queue  for all to authenticated using (true) with check (true);
create policy "auth_all_audit_runs"          on audit_runs          for all to authenticated using (true) with check (true);
create policy "auth_all_error_logs"          on error_logs          for all to authenticated using (true) with check (true);
